apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaproxy-deployment
spec:
  selector:
    matchLabels:
      app: javaproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: javaproxy
        azure.workload.identity/use: "true" 
    spec:
      serviceAccountName: workload-identity-sa-b3
      containers:
      - name: javaproxy
        image: apimaksecurityacr.azurecr.io/javaproxy:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaproxy-service
spec:
  selector:
    app: javaproxy
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: c5e2efd1-d9ed-422f-96ec-620f884c8e05
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa-b3
  namespace: default
